package com.yolt.providers.common.pis.paymentexecutioncontext.adapter.uk.initiate;

import com.yolt.providers.common.pis.paymentexecutioncontext.model.PaymentPreExecutionResultMapper;
import com.yolt.providers.common.pis.ukdomestic.InitiateUkDomesticScheduledPaymentRequest;

public interface UkInitiateScheduledPaymentPreExecutionResultMapper<PreExecutionResult> extends PaymentPreExecutionResultMapper<InitiateUkDomesticScheduledPaymentRequest, PreExecutionResult> {
}
